// Generated by gencpp from file master/deg.msg
// DO NOT EDIT!


#ifndef MASTER_MESSAGE_DEG_H
#define MASTER_MESSAGE_DEG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master
{
template <class ContainerAllocator>
struct deg_
{
  typedef deg_<ContainerAllocator> Type;

  deg_()
    : deg(0)  {
    }
  deg_(const ContainerAllocator& _alloc)
    : deg(0)  {
  (void)_alloc;
    }



   typedef uint16_t _deg_type;
  _deg_type deg;





  typedef boost::shared_ptr< ::master::deg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master::deg_<ContainerAllocator> const> ConstPtr;

}; // struct deg_

typedef ::master::deg_<std::allocator<void> > deg;

typedef boost::shared_ptr< ::master::deg > degPtr;
typedef boost::shared_ptr< ::master::deg const> degConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master::deg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master::deg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace master

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'master': ['/home/kid/ROS_main/src/master/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::master::deg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master::deg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master::deg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master::deg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master::deg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master::deg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master::deg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37c3b1a681be3c306e3679e4da1932c3";
  }

  static const char* value(const ::master::deg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37c3b1a681be3c30ULL;
  static const uint64_t static_value2 = 0x6e3679e4da1932c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::master::deg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master/deg";
  }

  static const char* value(const ::master::deg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master::deg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 deg\n\
";
  }

  static const char* value(const ::master::deg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master::deg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.deg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct deg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master::deg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master::deg_<ContainerAllocator>& v)
  {
    s << indent << "deg: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.deg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_MESSAGE_DEG_H
